name: ngs-environment
channels:
    - conda-forge
    - ngsolve
dependencies:
    - python=3.7
    - ngsolve-nogui
    - lxml
    - numpy
    - scipy
    - matplotlib
    - pyct
    - pip:
      - git+https://github.com/regpy/regpy.git@dev
      - webgui_jupyter_widgets
