#!/bin/bash

export PYVISTA_OFF_SCREEN=true
export PYVISTA_USE_PANEL=true
export PYVISTA_PLOT_THEME=document
export PYVISTA_AUTO_CLOSE=false

export LD_LIBRARY_PATH=$PWD
export TOOLBOX_PATH=$PWD/bart
export PYTHONPATH=$PWD/bart/python

export DISPLAY=:99.0
Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
sleep 3

exec "$@"
