#!/bin/bash

export PYVISTA_OFF_SCREEN=true
export PYVISTA_USE_PANEL=true
export PYVISTA_PLOT_THEME=document
export PYVISTA_AUTO_CLOSE=false

export LD_LIBRARY_PATH=$PWD/bart
export TOOLBOX_PATH=$PWD/bart
export PYTHONPATH=$PWD/bart/python

exec xvfb-run -s -s '-screen 0 1024x768x24' "$@"
